### ISSUE TITLE
uap-r fails to build with new YAML libraries

### ISSUE THREAD

**Issue by earino** [ua-parser/uap-r#2]
Greetings, when I go to install this package, I get:

```
internal_UaParser.cpp:54:23: error: no member named 'GetNextDocument' in 'YAML::Parser'
    CHECK(yaml_parser.GetNextDocument(regexes));
          ~~~~~~~~~~~ ^
```

Some googling led me to here: http://stackoverflow.com/questions/14365505/complete-example-yaml-program-on-http-code-google-com-p-yaml-cpp-wiki-howtopar which seems to imply that you built this code with the yaml-cpp 0.3.0 branch and the new 0.5.x branch has broken the API.

Thank you!

**Comment by hadley** [comment]
I have a problem at an earlier stage:

```
ccache clang++ -Qunused-arguments  -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Users/hadley/R/Rcpp/include"  -std=c++11 -fPIC  -Wall -mtune=core2 -g -O2  -c internal_UaParser.cpp -o internal_UaParser.o
In file included from internal_UaParser.cpp:1:
./internal_UaParser.h:6:10: fatal error: 'yaml-cpp/yaml.h' file not found
#include <yaml-cpp/yaml.h>
```

**Comment by Ironholds** [comment]
Yep; it takes 0.3. This package was the one that made me swear off using other peoples' compiled code if I couldn't rebuild it ;p
