### ISSUE TITLE
fatal error: 'boost/regex.hpp' file not found

### ISSUE THREAD

**Issue by juliakm** [ua-parser/uap-r#3]
When installing with "devtools::install_github("ua-parser/uap-r")", I get the following error: 

```
In file included from internal_UaParser.cpp:1:
./internal_UaParser.h:5:10: fatal error: 'boost/regex.hpp' file not found
#include <boost/regex.hpp>
```

**Comment by Ironholds** [comment]
@juliakm did you install the boost regex platform as the readme notes?

**Comment by juliakm** [comment]
I must have missed installing boost regex. Thanks.

**Comment by Ironholds** [comment]
@juliakm np! Let me know if you run into any problems installing it; I've had a devil of a time making them work nicely together on some platforms.
